### ISSUE TITLE
Wat doet class="notranslate"?

### ISSUE THREAD

**Issue by krijnhoetmer** [driezie/white-portfolio#3]
Goed dat je je al bewust bent van dit soort dingen!

Maar bedoel je met die `class` niet [het `translate` attribuut](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/translate)?

https://github.com/driezie/white-portfolio/blob/88d27d6311859d865f1876964c755205a7b337b6/index.html#L17C36-L17C36

**Comment by driezie** [comment]
Ik zat een klein beetje te zoeken naar of dit bestond en was er niet meer aan verder gegaan. Ik heb nu aan aanpassing gedaan zodat het nu wel goed werkt. zie [hier](https://github.com/driezie/white-portfolio/commit/9213f5b21244a62f2dca51da68761916f6919a34)
