### ISSUE TITLE
Wat zijn de headers hier?

### ISSUE THREAD

**Issue by krijnhoetmer** [driezie/white-portfolio#7]
Goed dat je al aan semantische markup en headers denkt!

De vraag is alleen: is een kop het deel dat het grootst is, of is de kop hier eigenlijk “Projects completed” (en de tekst eronder “30+”)?

https://github.com/driezie/white-portfolio/blob/88d27d6311859d865f1876964c755205a7b337b6/index.html#L53-L60

**Comment by driezie** [comment]
Eigenlijk hoort het samen 1 kop te zijn want ze zijn allebei even belangrijk anders weet je uberhoupt niet hoeveel of wat voor jaar experience ik heb. Weet u een betere manier hoe ik dit hierin kan zetten?

**Comment by krijnhoetmer** [comment]
Ik zou het juist omdraaien:

```html
 <div class="stat"> 
     <h2 class="stat-text">Projects Completed</h2>
     <p class="stat-number">30+</p>
 </div> 
 <div class="stat">
     <h2 class="stat-text">Years Experience</h2>
     <p class="stat-number">6+</p>
 </div> ```

**Comment by driezie** [comment]
Ik heb aanpassingen gedaan en deze inderdaad veranderd kwa volgorde. Bedankt!
