### ISSUE TITLE
Is dit content of decoratief?

### ISSUE THREAD

**Issue by krijnhoetmer** [driezie/white-portfolio#9]
[En hoort het dan in CSS of in HTML?](https://html.spec.whatwg.org/multipage/images.html#a-purely-decorative-image-that-doesn't-add-any-information) En wat is dan het `alt` attribuut?

https://github.com/driezie/white-portfolio/blob/9213f5b21244a62f2dca51da68761916f6919a34/index.html#L203

**Comment by driezie** [comment]
Ik heb hier aanpassingen op gedaan. Deze was inderdaad voor decoratief only!
